### PR TITLE
Gather all application windows and add owned windows as sub items

### PR DESCRIPTION
**Pull request by batzen**
With this PR all windows from Application.Current, from the same dispatcher, will be added to the tree and Window.OwnedWindows will be added as sub items to a window.

### CODE REVIEW

**Comment by cplotts** [comment]
This one is interesting ... I'd love to hear more about the scenarios where you find it useful. I would think an application with multiple modeless windows? I'm going to go ahead and merge it.

**Comment by cplotts** [comment]
Hey, by the way, can you make sure you use tabs instead of spaces? Thanks!

**Comment by batzen** [comment]
Will create a PR adding an .editorconfig if you'd like. Then tabs are used automatically if someone uses vs 2017 or the editorconfig extension.

**Comment by cplotts** [comment]
Sure. That sounds like something we should do.

**Comment by cplotts** [comment]
By the way, thank you for all the work you have done on Snoop! The community will definitely appreciate it ... especially once we get a release out.

**Pull request merged**
