### PR TITLE
Remove the functionality where all changes were copied to the clipboa…

### PR DESCRIPTION
**Pull request by weis0292**
…rd on Snoop closing.

Cory, please incorporate into your great product, Snoop.

### CODE REVIEW

**Comment by nwolverson** [comment]
Is there still a button for this? I remember this was super useful (but of course rather surprising to say the least when it's automatic)

**Comment by cplotts** [comment]
Yes, there is a keyboard shortcut that I did not remove ... and that is Ctrl-Shift-C. As with everything in Snoop, it is a secret. Don't tell.

**Comment by cplotts** [comment]
:)

**Comment by volleynerd** [comment]
OK - whew.  Glad it's not gone. I use this a lot (and often forget to copy
before closing, thus the feature to copy when close was added).

**Comment by cplotts** [comment]
Definitely not gone. It is a useful feature, but I've gotten several complaints about how important Snoop thought it was ... to take ownership of the clipboard without the user's consent.

**Comment by volleynerd** [comment]
Ya, absolutely agree.  thanks!

**Pull request merged**
